cfg:
  batch_size: 256
  classes: 200
  data_path: /ssd2/lyj/dataset/tiny-imagenet-200
  dataset_name: tiny-imagenet
  epochs: 1000
  gpus: 1
  model: ResNet
  optimizer: sgd
  optimizer_options:
    lr: 0.003
    momentum: 0.9
    nesterov: true
    weight_decay: 1.0e-05
  save_dir: ./saved
  save_freq: 5
  trainer_options:
    check_val_every_n_epoch: 5
  workers: 64
epoch_length: 391
