model : 'ResNet'
dataset_name : 'tiny-imagenet'
classes : 20
data_path : '/ssd2/lyj/dataset/tiny-imagenet-200'
save_dir : './saved'

workers : 64
epochs : 1000
batch_size : 20

save_freq : 5

optimizer : 'sgd'
optimizer_options:
  lr : 3e-3
  nesterov : true
  momentum : 0.9
  weight_decay : 1e-5

trainer_options:
  check_val_every_n_epoch : 5