model : 'ResNet'
dataset_name : 'tiny-imagenet'
classes : 200
data_path : '/mnt'
save_dir : './saved'
gpus : 0

workers : 0
epochs : 1000
batch_size : 64

save_freq : 5

optimizer : 'sgd'
optimizer_options:
  lr : 3e-3
  nesterov : true
  momentum : 0.9
  weight_decay : 1e-5

trainer_options:
  check_val_every_n_epoch : 5